/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'presence-simulator adapter settings': {
        'en': 'Adapter settings for presence-simulator',
        'de': 'Adaptereinstellungen für presence-simulator',
        'ru': 'Настройки адаптера для presence-simulator',
        'pt': 'Configurações do adaptador para presence-simulator',
        'nl': 'Adapterinstellingen voor presence-simulator',
        'fr': "Paramètres d'adaptateur pour presence-simulator",
        'it': "Impostazioni dell'adattatore per presence-simulator",
        'es': 'Ajustes del adaptador para presence-simulator',
        'pl': 'Ustawienia adaptera dla presence-simulator',
        'zh-cn': 'presence-simulator的适配器设置'
    },
    "Start": {
        "en": "Start",
        "de": "Start",
        "ru": "Начало",
        "pt": "Começar",
        "nl": "Begin",
        "fr": "Début",
        "it": "Inizio",
        "es": "comienzo",
        "pl": "Początek",
        "zh-cn": "开始"
    },
    "Schedules": {
        "en": "Schedules",
        "de": "Zeitpläne",
        "ru": "Расписание",
        "pt": "Horários",
        "nl": "Roosters",
        "fr": "Des horaires",
        "it": "Orari",
        "es": "Horarios",
        "pl": "Harmonogramy",
        "zh-cn": "时间表"
    },
    "States": {
        "en": "States",
        "de": "Zustände",
        "ru": "состояния",
        "pt": "Estados",
        "nl": "Staten",
        "fr": "États",
        "it": "stati",
        "es": "Estados",
        "pl": "Stany",
        "zh-cn": "状态"
    },
    "Result": {
        "en": "Result",
        "de": "Ergebnis",
        "ru": "Результат",
        "pt": "Resultado",
        "nl": "Resultaat",
        "fr": "Résultat",
        "it": "Risultato",
        "es": "Resultado",
        "pl": "Wynik",
        "zh-cn": "结果"
    },
    "Add schedule": {
        "en": "Add schedule",
        "de": "Zeitplan hinzufügen",
        "ru": "Добавить расписание",
        "pt": "Adicionar agendamento",
        "nl": "Schema toevoegen",
        "fr": "Ajouter un horaire",
        "it": "Aggiungi programma",
        "es": "Agregar horario",
        "pl": "Dodaj harmonogram",
        "zh-cn": "新增时间表"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Nom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Nazwa",
        "zh-cn": "名称"
    },
    "Earliest start time": {
        "en": "Earliest start time",
        "de": "Frühester Startzeitpunkt",
        "ru": "Самое раннее время начала",
        "pt": "Horário de início mais cedo",
        "nl": "Vroegste starttijd",
        "fr": "Heure de début au plus tôt",
        "it": "Primo orario di inizio",
        "es": "Hora de inicio más temprana",
        "pl": "Najwcześniejszy czas rozpoczęcia",
        "zh-cn": "最早开始时间"
    },
    "Latest start time": {
        "en": "Latest start time",
        "de": "Spätester Startzeitpunkt",
        "ru": "Самое позднее время начала",
        "pt": "Última hora de início",
        "nl": "Laatste starttijd",
        "fr": "Dernière heure de début",
        "it": "Ora di inizio più recente",
        "es": "Hora de inicio más reciente",
        "pl": "Ostatni czas rozpoczęcia",
        "zh-cn": "最晚开始时间"
    },
    "Activated": {
        "en": "Activated",
        "de": "Aktiviert",
        "ru": "активированная",
        "pt": "ativado",
        "nl": "geactiveerde",
        "fr": "Activé",
        "it": "attivato",
        "es": "Activado",
        "pl": "Aktywowany",
        "zh-cn": "活性"
    },
    "Schedule to edit": {
        "en": "Schedule to edit",
        "de": "Zeitplan zum Bearbeiten",
        "ru": "Расписание для редактирования",
        "pt": "Programar para editar",
        "nl": "Schema om te bewerken",
        "fr": "Planifier la modification",
        "it": "Pianifica la modifica",
        "es": "Programar para editar",
        "pl": "Zaplanuj edycję",
        "zh-cn": "安排编辑"
    },
    "Add state": {
        "en": "Add state",
        "de": "Zustand hinzufügen",
        "ru": "Добавить штат",
        "pt": "Adicionar estado",
        "nl": "Staat toevoegen",
        "fr": "Ajouter un état",
        "it": "Aggiungi stato",
        "es": "Agregar estado",
        "pl": "Dodaj stan",
        "zh-cn": "添加状态"
    },
    "ID": {
        "en": "ID",
        "de": "ID",
        "ru": "ID",
        "pt": "ID",
        "nl": "ID",
        "fr": "ID",
        "it": "ID",
        "es": "ID",
        "pl": "ID",
        "zh-cn": "ID"
    },
    "State start": {
        "en": "State start",
        "de": "Zustand Start",
        "ru": "Государственный старт",
        "pt": "Início do estado",
        "nl": "Staat start",
        "fr": "Début de l'état",
        "it": "Inizio stato",
        "es": "Inicio del estado",
        "pl": "Stan początkowy",
        "zh-cn": "状态开始"
    },
    "State end": {
        "en": "State end",
        "de": "Zustand Ende",
        "ru": "Государство конец",
        "pt": "Fim do estado",
        "nl": "Staat einde",
        "fr": "Fin de l'état",
        "it": "Fine dello stato",
        "es": "Fin del estado",
        "pl": "Koniec stanu",
        "zh-cn": "状态结束"
    },
    "Working time": {
        "en": "Working time",
        "de": "Arbeitszeit",
        "ru": "Рабочее время",
        "pt": "Expediente",
        "nl": "Werktijd",
        "fr": "Temps de travail",
        "it": "Orario di lavoro",
        "es": "Tiempo de trabajo",
        "pl": "Czas pracy",
        "zh-cn": "工作时间"
    },
    "Probability": {
        "en": "Probability",
        "de": "Wahrscheinlichkeit",
        "ru": "Вероятность",
        "pt": "Probabilidade",
        "nl": "Waarschijnlijkheid",
        "fr": "Probabilité",
        "it": "Probabilità",
        "es": "Probabilidad",
        "pl": "Prawdopodobieństwo",
        "zh-cn": "可能性"
    }
};